version: "1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=assignment_database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - SCREENSHOT_JOB_SCHEDULE = '* * * * *'
      - CLOUDINARY_CLOUD_NAME='dikvqmh3i'
      - CLOUDINARY_API_KEY='724338923291159'
      - CLOUDINARY_API_SECRET='1K2vYzhUzLiV46NxLkiBJB1G7X8'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=assignment_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
